modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="railguncoin"
version="1.0.0"
displayName="Railgun Coin"
description='''
Immersive Engineering のレールガンに、炸裂・ロックオン機能を持つ銀のコイン弾を追加します。
'''

[[mixins]]
config="railguncoin.mixins.json"

[[dependencies.railguncoin]]
modId="neoforge"
type="required"
versionRange="[21.1.249,)"
ordering="NONE"
side="BOTH"

[[dependencies.railguncoin]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.railguncoin]]
modId="immersiveengineering"
type="required"
versionRange="[12.4.2-194,12.4.3)"
ordering="AFTER"
side="BOTH"

[[dependencies.railguncoin]]
modId="create"
type="required"
versionRange="[6.0.0,)"
ordering="AFTER"
side="BOTH"
