modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Immersive Engineering のレールガンに、炸裂・ロックオン機能を持つコイン弾を追加します。
'''

[[mixins]]
config="railguncoin.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="immersiveengineering"
type="required"
versionRange="[12.4.2-194,12.4.3)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="[6.0.10,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="createaddition"
type="required"
versionRange="[1.6.0,1.7.0)"
ordering="AFTER"
side="BOTH"
